from odoo import fields, models, api
from odoo.exceptions import UserError, ValidationError


class PntCoaContent(models.Model):
    _name = "pnt.coa.content"
    _description = "COA Content per Language"

    # Relaci√≥n con el modelo PntCoa
    coa_id = fields.Many2one(
        "pnt.coa", string="COA Reference", required=True, ondelete="cascade"
    )
    language_code = fields.Char(string="Language Code", required=True)
    coa_body = fields.Html(string="COA Body")
    multicolor_body = fields.Html(string="Multicolor Body")
    components_body = fields.Html(string="Components Body")
